[package]
name = "rustjni"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustjni"
crate-type = ["cdylib"]

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
jni = "0.19.0"