// Generated by jextract

package org.hello;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$0 {

    static final FunctionDescriptor helloworld$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle helloworld$MH = RuntimeHelper.downcallHandle(
        helloworld_h.LIBRARIES, "ffm_jextract",
        "()V",
        constants$0.helloworld$FUNC, false
    );
    static final FunctionDescriptor printstruct$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle printstruct$MH = RuntimeHelper.downcallHandle(
        helloworld_h.LIBRARIES, "printstruct",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$0.printstruct$FUNC, false
    );
    static final FunctionDescriptor getstruct$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_POINTER.withName("name"),
        C_INT.withName("age"),
        MemoryLayout.paddingLayout(32),
        C_DOUBLE.withName("height")
    ).withName("student"));
    static final MethodHandle getstruct$MH = RuntimeHelper.downcallHandle(
        helloworld_h.LIBRARIES, "getstruct",
        "()Ljdk/incubator/foreign/MemorySegment;",
        constants$0.getstruct$FUNC, false
    );
}


